[29/Jul/2020 02:02:35] DEBUG [api.views:26] now running function find_closest_network_node
[29/Jul/2020 02:02:35] DEBUG [api.views:26] now running function find_closest_network_node
[29/Jul/2020 02:02:41] DEBUG [api.views:26] now running function find_closest_network_node
[29/Jul/2020 02:02:41] DEBUG [api.views:26] now running function find_closest_network_node
[29/Jul/2020 02:02:46] DEBUG [api.views:26] now running function find_closest_network_node
[29/Jul/2020 02:02:46] DEBUG [api.views:26] now running function find_closest_network_node
[29/Jul/2020 12:25:46] DEBUG [api.views:26] now running function find_closest_network_node
[29/Jul/2020 12:25:46] DEBUG [api.views:26] now running function find_closest_network_node
[30/Jul/2020 01:33:27] ERROR [api.views:672] error exporting model algorithm
[30/Jul/2020 01:33:27] ERROR [api.views:673] Traceback (most recent call last):
  File "C:\Projects_Python\python-geospatial-analysis-cookbook-master\web_analysis\api\views.py", line 670, in rout_finding
    return Response(dist[0])
KeyError: 0

[30/Jul/2020 02:46:55] ERROR [api.views:684] error exporting model algorithm
[30/Jul/2020 02:46:55] ERROR [api.views:685] Traceback (most recent call last):
  File "C:\Python\lib\site-packages\django\http\response.py", line 51, in __init__
    self.status_code = int(status)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'list'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Projects_Python\python-geospatial-analysis-cookbook-master\web_analysis\api\views.py", line 682, in rout_finding
    return Response(final_pop[0]['route'][0], route_sequence )
  File "C:\Python\lib\site-packages\rest_framework\response.py", line 30, in __init__
    super().__init__(None, status=status)
  File "C:\Python\lib\site-packages\django\template\response.py", line 36, in __init__
    super().__init__('', content_type, status, charset=charset)
  File "C:\Python\lib\site-packages\django\http\response.py", line 290, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Python\lib\site-packages\django\http\response.py", line 53, in __init__
    raise TypeError('HTTP status code must be an integer.')
TypeError: HTTP status code must be an integer.

